### ISSUE TITLE
Flask app won't start when there is an '-' in the project name

### ISSUE THREAD

**Issue by Grepsy** [romainberger/yeoman-flask#11]
```
~/Workspace (master) » python server.py
  File "server.py", line 2
    from flask-monkeys import flask-monkeys
              ^
SyntaxError: invalid syntax
```

**Comment by romainberger** [comment]
You [can't use a dash in a python package name](http://www.python.org/dev/peps/pep-0008/#package-and-module-names), this will throw a syntax error (as you've seen). You'll have to rename your app.
