### ISSUE TITLE
update bootstrap to v3.1.1

### ISSUE THREAD

**Issue by bsdlp** [romainberger/yeoman-flask#22]
https://github.com/twbs/bootstrap/releases/tag/v3.1.1

**Comment by mgcdanny** [comment]
+1

**Comment by romainberger** [comment]
Hi, sorry for the delay, I'll try to work on it asap.

I'm not using Flask anymore so if somebody wants to take over the project or become a maintainer I can do that.

**Comment by romainberger** [comment]
Done in #25 by @sliceolife
